server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 47.81.210.196;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 503;
    }
}
